version: '3'

services:
  angular-app:
    build: .
    ports:
      - 4200:4200
    volumes:
      - ./app:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
    stdin_open: true
    restart: always